name: yellow express
favicon: null
layout_spectrum: 0.25573
typography_spectrum: 0.49561
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#cacaca'
    - '#6c6c6c'
    - '#fafa5e'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
