name: yellow express
favicon: null
layout_spectrum: 0.9558286385145038
typography_spectrum: 0.7051919491495937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7473647776059806
  lightness: 0.09894456621259451
  saturation: 0.057543681701645255
  rhythmicContrast: 0.4895380660891533
purpose: []
